project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Job Market Analysis"
  author:
    - Mohsin Chougale (mc5491)
    - Shikhar Johri (sj3327)
  repo-url: https://github.com/mohsinchougale/Job-Market-Analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


