# Data

## Description

### Job Openings and Labor Turnover Survey (JOLTS) Dataset {-}

The [Job Openings and Labor Turnover Survey (JOLTS)](https://www.bls.gov/jlt/) provides national estimates of rates and levels for various labor market dynamics. The survey covers job openings, hires, and total separations, further broken down into quits, layoffs and discharges, and other separations.

#### **Dataset Files** {-}

The survey data is accessible through FTP files available in the BLS internet sub-directory [pub/time.series/jt](https://download.bls.gov/pub/time.series/jt/). These files include information on contacts, current data, all items, job openings, hires, total separations, quits, layoffs and discharges, other separations, and various mapping files providing additional context.

#### **Series File** {-}

The [jt.series](https://download.bls.gov/pub/time.series/jt/jt.series) file serves as a key component, detailing the structure and format of series identification codes. Each code includes information on seasonality, industry, state, area, size class, data element, rate level, and footnote codes. This information allows for precise identification and categorization of data series.

#### **Mapping Files** {-}

Various mapping files, such as [jt.area](https://download.bls.gov/pub/time.series/jt/jt.area), [jt.dataelement](https://download.bls.gov/pub/time.series/jt/jt.dataelement), [jt.footnote](https://download.bls.gov/pub/time.series/jt/jt.footnote), [jt.industry](https://download.bls.gov/pub/time.series/jt/jt.industry), [jt.period](https://download.bls.gov/pub/time.series/jt/jt.period), [jt.ratelevel](https://download.bls.gov/pub/time.series/jt/jt.ratelevel), [jt.seasonal](https://download.bls.gov/pub/time.series/jt/jt.seasonal), [jt.sizeclass](https://download.bls.gov/pub/time.series/jt/jt.sizeclass), and [jt.state](https://download.bls.gov/pub/time.series/jt/jt.state), provide textual descriptions for the codes used in the series identification. These mapping files enhance the interpretability of the data.



The JOLTS dataset is a valuable resource for understanding labor market dynamics, offering detailed and well-organized information that enables researchers, policymakers, and analysts to gain insights into the trends and patterns shaping the employment landscape.

## Research Plan

1. **Data Collection**: As, the dataset is divide into different files, containing job openings, hires, separations, and industry specifics, we collect the files and convert into csv format for further analysis.

2. **Preprocessing**: Cleaning and organizing the data. Here we also analyse any missing values in our dataset.

3. **Exploratory Analysis**: Identify trends, patterns, and correlations in job data across industries and regions.

4. **Addressing Research Questions**:
   - **Industry Insights**: Identify high-demand industries aligning with skills.
   - **Regional Variations**: Map job trends across regions for better prospects.
   - **Job Market Trends**: Analyze sectoral shifts over time for informed career choices.
   - **Turnover Rates**: Assess job stability and growth potential in different sectors.
   - **Seasonal Trends**: Study seasonal impacts on job openings and separations.

5. **Statistical Insight**: Use models for predictive analysis or understanding influencing factors.

6. **Interactive component**: Using D3, we provide engaging graphs to gain clear understanding on the dataset 

6. **Reporting**: Summarize the findings, highlight insights, and present recommendations for career planning and job search strategies.

## Missing value analysis

For most of our files we do not observe any missing values in the dataset. Majorly, the footnote_codes values are found to be missing in the datasets (wherever it referred). This may be due to the fact that this dataset only have 1 type of footnote which may be not linked to most of the data values.
Particularly in the mapping files of industry dataset we observe display_level, selectable and sort_sequence to be missing from the dataset (in each 14.3% values are NA)


```{r}
library(tidyverse)

folder_path <- "C:\\Users\\A-Team\\Documents\\MSDS\\EDAV\\Assignments\\final project\\final data"

csv_files <- list.files(folder_path, pattern = "\\.csv$", full.names = TRUE)

for (file in csv_files) {
  data <- read.csv(file)

  csv_file_name <- strsplit(file, "/")[[1]][2]

  missing_summary <- data %>%
    summarise_all(~ mean(is.na(.)) * 100) %>%
    gather(key = "variable", value = "missing_percentage") %>%
    arrange(desc(missing_percentage))

  missing_value_graph <- ggplot(missing_summary, aes(x = reorder(variable, -missing_percentage), y = missing_percentage)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    geom_text(data = subset(missing_summary, missing_percentage != 0),
              aes(label = round(missing_percentage, 1)), vjust = -0.5, size = 3) +
    labs(title = paste("Missing Value Summary (", csv_file_name,")"),
         x = "Variables",
         y = "missing Values (%)")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  print(missing_value_graph )
}

```

